<div style="margin-top: 10px; margin-left: 2%; width: 96%; margin-bottom: 10px;">
<h3>Tentang Kami</h3>
<div class="page-content"><p>Assalamu'alaikum wr wb</p>

 <p>Alhamdulillah dengan berkah dan rahmat Allah SWT&nbsp; akhirnya <strong style="font-weight: normal;">Prima Sari</strong> dapat menjumpai pecinta <em>batik </em>diseluruh nusantara. Untuk melestarikan budaya yang agung ini, kami menyediakan <strong><em>baju batik</em></strong> berkualitas yang akan tampil di tengah persaingan produk fashion dari seluruh dunia. </p>

 <p>Sebagai wujud kebanggaan kami terhadap <em>budaya</em> <em>batik</em> karya nenek moyang yang luar biasa tinggi nilainya, kami mengemas <em style="font-style: italic;">Batik</em><em> Indonesia </em>dalam wadah yang lebih menarik di <strong style="font-weight: normal;">Prima Sari</strong>. <strong style="font-weight: normal;">Kami</strong> akan berusaha memberikan yang terbaik, bukan hanya untuk konsumen&nbsp; tapi juga untuk kelestarian <em>Batik Indonesia.</em> Dengan <strong style="font-weight: normal;">hadirnya Prima Sari</strong> anda akan semakin mencintai produk kebanggaan negeri.<em style="font-weight: bold;"> <br></em></p>

 <p><strong>Filosofi Prima Sari :</strong></p>

 <p>Disamping kualitas seni <strong>motif batik</strong> yang tinggi,&nbsp; dan unsur budaya di balik <em>filosofi </em><em>Batik</em>, karya para leluhur kita ini ternyata juga memiliki ragam fariasi <em>motif batik</em> yang banyak sekali jumlahnya dan dapat berkembang tanpa batas<em>.</em> Diseluruh Indonesia <em>batik</em> tampil dengan ciri budaya daerah asal masing2, mulai dari <em>batik pekalongan, batik madura, batik yogyakarta, batik solo</em> semua memiliki ciri khas sendiri, yang merupakan hasil akulturasi budaya selama berabad-abad. Aneka <em>motif </em><em style="font-style: italic;">batik</em><em> klasik</em> Indonesia juga merupakan sumber inspirasi desainer di seluruh dunia karena keunikan dan ragam motifnya. Nilai esential inilah yang kami angkat sehingga kami mengambil nama&nbsp; <strong style="font-weight: bold;">Prima Sari</strong>. Kualitas warna yang bagus, bahan yang ramah lingkungan, <em>proses pembuatan batik </em>yang rumit, motif yang cantik semua ada dalam<em> Batik</em>, tak salah jika <em>Batik</em> dinilai sangat Unik. Nilai ini yang mempertahankan <em>eksistensi batik</em> sampai sekarang. Tak mudah kita jumpai produk <em>Batik </em>di pasaran yang bertahan lama, kekayaan <em>motif batik </em>membuanyaselalu berkembang dan berubah menurut tingkat kreatifitas <strong>seniman batik</strong>. Untuk menghormati <em>Batik</em> dan budayanya, <strong style="font-weight: normal;">Prima Sari</strong> hadir ditengah anda..</p>

 <p><strong>Kualitas Produk dan Jasa kami :</strong></p>

 <p><strong style="font-weight: normal;">Prima Sari</strong> memberikan harga yang membuat anda nyaman menggunakanya. Dapatkan harga yang sama ketika anda bertransaksi di <em>pusat pengrajin batik</em>. Silahkan buktikan dan datang ke basecamp kami&nbsp; di <strong style="font-weight: normal;">kota Bukittinggi</strong><em>. </em>Kenyamanan tersebut yang berusaha kami angkat di <strong style="font-weight: normal;">Prima Sari</strong>. Kini dirumah anda sendiri anda dapat jalan-jalan dan cuci mata menikmati keindahan&nbsp; aneka <em>model baju batik</em> nusantara. Dapatkan aneka jenis <em>produk batik</em> favorit anda dengan mudah dan murah, dari <em>baju batik pria, baju batik wanita, baju batik anak, dress batik, dan perlengkapan batik lainya.</em> Order anda akan diproses dengan cepat oleh sistem kami.</p>

 <p>Untuk meningkatkan kelestarian batik, kami juga menyediakan aneka produk <em>batik modern</em>, aneka model <em>baju batik modis</em> yang dapat melengkapi dan mempercantik gaya anda. Bersama <strong style="font-weight: normal;">Prima Sari</strong> akan lebih mudah menentukan style anda sendiri, tinggal memadu padankan sesuai dengan karakter<em>. </em>Andapun dapat tampil trendy dengan tetap mengenakan identitas sebagai pewaris budaya<strong> Batik Indonesia</strong> yang tersohor. Selamat berbelanja, salam Cinta Batik Indonesia ;) </p></div>
		</div>